<a href="https://colab.research.google.com/github/gaganbn007/gaganbn007/blob/main/gagan_numpy_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as npa 
npa= np.array([1, 2, 3])
print(npa)

[1 2 3]


In [ ]:
import numpy as npp
a = npp.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a=np.zeros(2)
print(a)

[0. 0.]


In [ ]:
import numpy as np
a=np.ones(4)
print(a)

[1. 1. 1. 1.]


In [ ]:
import numpy as np
ab=np.empty(4)
print(ab)

[1. 1. 1. 1.]


In [ ]:
import numpy as np
a=np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.arange(2,9,2)
print(a)

[2 4 6 8]


In [ ]:
y = np.ones(2, dtype=int)
print(y)
y

[1 1]


array([1, 1])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)


a=np.delete(a, 1)
print(a)

[1 2 3 4 5 6 7 8]
[1 3 4 5 6 7 8]


In [ ]:
a = np.array([19, 22, 34, 14, 55, 76, 47, 8])
print(a)


a=np.sort(a)
print(a)

[19 22 34 14 55 76 47  8]
[ 8 14 19 22 34 47 55 76]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)

[[1 2 3]
 [4 5 6]]
dimensions =  2


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 33], [44, 55, 66]]])
a=arr.ndim
b=arr.size
print(arr) 
print("dimensions = ", a)
print("size = ", b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
dimensions =  3
size =  12


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print("dimension= ", a.ndim)
print(b)
print("dimension= ", b.ndim)
print(c)
print("dimension= ", c.ndim)
print(d)
print("dimension= ", d.ndim)


42
dimension=  0
[1 2 3 4 5]
dimension=  1
[[1 2 3]
 [4 5 6]]
dimension=  2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension=  3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


In [ ]:
a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
